import Foundation

struct MockData {
    static let servers: [Server] = [
        Server(
            id: "CA-SFO-001",
            countryName: "California",
            countryCode: "CA",
            city: "San Francisco",
            load: 0.45,
            host: "sfo-1.wiredogvpn.com",
            latencyMs: 42,
            ipAddress: "198.51.100.42",
            latitude: 37.7749,
            longitude: -122.4194,
            isFavorite: false
        ),
        Server(
            id: "TX-DFW-001",
            countryName: "Texas",
            countryCode: "TX",
            city: "Dallas",
            load: 0.62,
            host: "dfw-1.wiredogvpn.com",
            latencyMs: 95,
            ipAddress: "203.0.113.98",
            latitude: 32.7767,
            longitude: -96.7970,
            isFavorite: false
        ),
        Server(
            id: "NY-NYC-001",
            countryName: "New York",
            countryCode: "NY",
            city: "New York City",
            load: 0.75,
            host: "nyc-1.wiredogvpn.com",
            latencyMs: 175,
            ipAddress: "192.0.2.163",
            latitude: 40.7128,
            longitude: -74.0060,
            isFavorite: false
        ),
        Server(
            id: "FL-MIA-001",
            countryName: "Florida",
            countryCode: "FL",
            city: "Miami",
            load: 0.35,
            host: "mia-1.wiredogvpn.com",
            latencyMs: 65,
            ipAddress: "198.51.100.108",
            latitude: 25.7617,
            longitude: -80.1918,
            isFavorite: false
        ),
        Server(
            id: "WA-SEA-001",
            countryName: "Washington",
            countryCode: "WA",
            city: "Seattle",
            load: 0.28,
            host: "sea-1.wiredogvpn.com",
            latencyMs: 38,
            ipAddress: "203.0.113.151",
            latitude: 47.6062,
            longitude: -122.3321,
            isFavorite: false
        ),
        Server(
            id: "IL-CHI-001",
            countryName: "Illinois",
            countryCode: "IL",
            city: "Chicago",
            load: 0.55,
            host: "chi-1.wiredogvpn.com",
            latencyMs: 110,
            ipAddress: "192.0.2.130",
            latitude: 41.8781,
            longitude: -87.6298,
            isFavorite: false
        ),
        Server(
            id: "GA-ATL-001",
            countryName: "Georgia",
            countryCode: "GA",
            city: "Atlanta",
            load: 0.42,
            host: "atl-1.wiredogvpn.com",
            latencyMs: 78,
            ipAddress: "198.51.100.46",
            latitude: 33.7490,
            longitude: -84.3880,
            isFavorite: false
        ),
        Server(
            id: "MA-BOS-001",
            countryName: "Massachusetts",
            countryCode: "MA",
            city: "Boston",
            load: 0.58,
            host: "bos-1.wiredogvpn.com",
            latencyMs: 130,
            ipAddress: "203.0.113.130",
            latitude: 42.3601,
            longitude: -71.0589,
            isFavorite: false
        ),
        Server(
            id: "AZ-PHX-001",
            countryName: "Arizona",
            countryCode: "AZ",
            city: "Phoenix",
            load: 0.68,
            host: "phx-1.wiredogvpn.com",
            latencyMs: 55,
            ipAddress: "192.0.2.130",
            latitude: 33.4484,
            longitude: -112.0742,
            isFavorite: false
        ),
        Server(
            id: "CO-DEN-001",
            countryName: "Colorado",
            countryCode: "CO",
            city: "Denver",
            load: 0.51,
            host: "den-1.wiredogvpn.com",
            latencyMs: 88,
            ipAddress: "198.51.100.130",
            latitude: 39.7392,
            longitude: -104.9903,
            isFavorite: false
        ),
        Server(
            id: "NV-LAS-001",
            countryName: "Nevada",
            countryCode: "NV",
            city: "Las Vegas",
            load: 0.39,
            host: "las-1.wiredogvpn.com",
            latencyMs: 50,
            ipAddress: "203.0.113.152",
            latitude: 36.1699,
            longitude: -115.1398,
            isFavorite: false
        ),
        Server(
            id: "PA-PHL-001",
            countryName: "Pennsylvania",
            countryCode: "PA",
            city: "Philadelphia",
            load: 0.48,
            host: "phl-1.wiredogvpn.com",
            latencyMs: 145,
            ipAddress: "192.0.2.130",
            latitude: 39.9526,
            longitude: -75.1652,
            isFavorite: false
        ),
        Server(
            id: "OH-CMH-001",
            countryName: "Ohio",
            countryCode: "OH",
            city: "Columbus",
            load: 0.33,
            host: "cmh-1.wiredogvpn.com",
            latencyMs: 102,
            ipAddress: "198.51.100.130",
            latitude: 39.9612,
            longitude: -82.9988,
            isFavorite: false
        ),
        Server(
            id: "TN-BNA-001",
            countryName: "Tennessee",
            countryCode: "TN",
            city: "Nashville",
            load: 0.52,
            host: "bna-1.wiredogvpn.com",
            latencyMs: 120,
            ipAddress: "203.0.113.130",
            latitude: 36.1627,
            longitude: -86.7816,
            isFavorite: false
        ),
        Server(
            id: "NC-CLT-001",
            countryName: "North Carolina",
            countryCode: "NC",
            city: "Charlotte",
            load: 0.64,
            host: "clt-1.wiredogvpn.com",
            latencyMs: 160,
            ipAddress: "192.0.2.152",
            latitude: 35.2271,
            longitude: -80.8431,
            isFavorite: false
        ),
        Server(
            id: "UT-SLC-001",
            countryName: "Utah",
            countryCode: "UT",
            city: "Salt Lake City",
            load: 0.71,
            host: "slc-1.wiredogvpn.com",
            latencyMs: 0,
            ipAddress: "198.51.100.130",
            latitude: 40.7608,
            longitude: -111.8910,
            isFavorite: false
        ),
        Server(
            id: "OR-PDX-001",
            countryName: "Oregon",
            countryCode: "OR",
            city: "Portland",
            load: 0.73,
            host: "pdx-1.wiredogvpn.com",
            latencyMs: 0,
            ipAddress: "203.0.113.130",
            latitude: 45.5152,
            longitude: -122.6784,
            isFavorite: false
        ),
        Server(
            id: "VA-RIC-001",
            countryName: "Virginia",
            countryCode: "VA",
            city: "Richmond",
            load: 0.59,
            host: "ric-1.wiredogvpn.com",
            latencyMs: 135,
            ipAddress: "192.0.2.130",
            latitude: 37.5407,
            longitude: -77.4360,
            isFavorite: false
        ),
    ]

    static let currentStats = ConnectionStats(
        downloadSpeed: 25.0,
        uploadSpeed: 18.5,
        connectionTime: 5149,
        dataTransferred: 2.4
    )

    static let defaultSettings = VPNSettings()
}
